// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserManagementService.Domain.Entities;

public partial class tbl_User
{
    [Key]
    public Guid UserId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Required]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Required]
    [Unicode(false)]
    public string SecurityKey { get; set; }

    [Required]
    [Unicode(false)]
    public string License { get; set; }

    [StringLength(500)]
    public string FullName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    public int? TimeZone { get; set; }

    public bool? IsActive { get; set; }

    [StringLength(500)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(500)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }

    public bool? IsSystem { get; set; }
}